### PR TITLE
Initial work on error payloads

### PR DESCRIPTION
**Pull request by RobertLowe**
Hey,

Here's the work for errors payloads. I know we talked about moving `errors` inside the records payload, but that still feels awkward to me, I mean what if the model has an `errors` property, should we use `_errors`, additional where should we be injecting the errors payload type. Inside `createInputType`?

Cheers,
- Rob

### CODE REVIEW

**Comment by RobertLowe** [comment]
Follow up, after we get the above stored we can address the other operations `...Many`, `remove...`, etc

**Comment by RobertLowe** [comment]
Okay, this uses `ErrorInterface` 👍  and flattens array level 👍

**Comment by nodkz** [comment]
@RobertLowe good catch for ...Many resolvers.

I think that if a client provides for us an array with input data then we should return some array with result data in payload. I suppose that `records` field which is an array of shape for singular response is quite a good and reusable solution for our clients (the can write helper functions which read singular mutations and use them in iterators for plural resolvers).

```graphql
type xxxManyPayload {
  records: xxxManyPayloadRecords
  hasErrors: Boolean!  # <--- need to find a good name for this field
}

type xxxManyPayloadRecords {
  recordId: ID
  record: Entity
  errors: ErrorInterface
}
```

About `hasErrors` field: we should provide a convenient way to frontenders for checking do they have errors for some operation or not. And I think that the most convenient way to determine is there an error or not - check some field rather than traverse some arrays. And if this field has error flag, then start traversing errors if needed to display them somehow to end-users. But I not sure `hasErrors` is a good name or not. What are your thoughts?

**Comment by RobertLowe** [comment]
@nodkz thanks, also just resolved tests.

How about? Just `errors`, `hasErrors` sound better, but if we just send `errors` back as boolean it's more uniform to the other APIs

```graphql
type xxxManyPayload {
  records: xxxManyPayloadRecords
  errors: Boolean!  # <--- need to find a good name for this field
}

type xxxManyPayloadRecords { # <---- try to keep the same payload shape of *One resolvers
  recordId: ID
  record: Entity
  errors: ErrorInterface
}
```

Yeah, this is what I was thinking too.

**Comment by nodkz** [comment]
Nope, just `errors` name is a bad idea for Boolean field. Clients may be confused by such query:

```graphql
mutation {
  userCreateMany(...) {
     records {
       errors # <--- real array with errors' messages
     }
     errors # <--- just boolean value
  }
}
```

**Comment by RobertLowe** [comment]
Yeah, I'm cool with `hasErrors`. However, what do we do in the case of runtime errors, etc an exception like no mongo connection, would that just appear in all sub-documents.

Maybe something like:

```graphql
type xxxManyPayload {
  records: xxxManyPayloadRecords
  hasRecordErrors: Boolean
  error(s): [ErrorInterface] # <- runtime/ hard errors
}

type xxxManyPayloadRecords {
  recordId: ID
  record: Entity
  errors: ErrorInterface # <-- nested validation, runtime, etc errors
}
```

**Comment by RobertLowe** [comment]
Follow up, what should be finished on this PR to close it?

**Comment by nodkz** [comment]
I've just improved `createOne` resolver – if `errors` field is not requested in graphql query then throw top-level error. See the following test suite https://github.com/graphql-compose/graphql-compose-mongoose/pull/248/commits/da05d7a771dc5860f3a85fdfa092ca7d5217c57a#diff-db6bb76152461b1e807ccac62fe81271

What need to do
- [ ] improve other resolvers with throwing error on top-level (maybe need to write a common wrapper for resolvers which will check `resolveParams.projection.errors` and throw Error or just return error inside the result. For now, we have duplicate code in resolvers).
- [ ] decide what to to with async validators (because `validateSync` skips async checks)
- [ ] write additional tests 
  - [ ] with async validator
  - [ ] with runtime error for checking that it returns in mutation payload (if errors fields is requested in query)
  - [ ] with runtime error for checking that it throws in top-level (if errors fields is not requested in query)

**Comment by nodkz** [comment]
Also I found that `ValidationError` has `value` property from client which causes the validation error. So I think it will be nice to return it https://github.com/graphql-compose/graphql-compose-mongoose/pull/248/commits/da05d7a771dc5860f3a85fdfa092ca7d5217c57a#diff-dd2f0072f8e0f435a2b858dcba4c6aafR113

**Comment by RobertLowe** [comment]
Thanks for the improvements!

**Comment by nodkz** [comment]
### As an example of `a common wrapper for resolvers`

In one of our internal app, we are using such wrapper for our mutations
- `status: String` - it's a flag about the operation status (we are using `hasError` this is much better solution)
- `query: Query` - it allows to request data from graph after mutation in one request (more details https://graphql-rules.com/rules/mutation-payload-query)

So in such manner we can catch errors from `resolve` method and decide what to do - return it in the payload or throw to the top-level.

```ts
import {
  TContext,
  Extensions,
  GraphQLFieldResolver,
  ObjectTypeComposer,
  ObjectTypeComposerFieldConfigAsObjectDefinition,
  ObjectTypeComposerAsObjectDefinition,
  ObjectTypeComposerFieldConfig,
  ObjectTypeComposerArgumentConfigMapDefinition,
  schemaComposer,
} from '@pskz/app-server';
import { GraphQLResolveInfo } from 'graphql';

export interface PayloadTypeConfig {
  name: string;
  fields: {
    [key: string]: ObjectTypeComposerFieldConfig<any, TContext>;
  };
}

export interface PayloadData {
  recordId: string;
  status?: string;
}

export interface PayloadConfig<TArgs, TFields = any> {
  type: ObjectTypeComposerAsObjectDefinition<any, TContext>;
  args?: ObjectTypeComposerArgumentConfigMapDefinition<TArgs>;
  resolve?: GraphQLFieldResolver<TArgs, TFields>;
  subscribe?: GraphQLFieldResolver<TArgs, TFields>;
  deprecationReason?: string | null;
  description?: string | null;
  extensions?: Extensions;
  [key: string]: any;
}

export function generateMutationPayload<TArgs>(fc: PayloadConfig<TArgs>) {
  let type: ObjectTypeComposer;
  try {
    type = schemaComposer.createObjectTC(fc.type);
  } catch (e) {
    throw new Error('Cannot wrap mutation payload cause it returns non-object type.');
  }
  type.addFields({
    status: 'String',
    query: 'Query!',
  });

  const oldResolve =
    fc.resolve ||
    async function (_source: any, _args: TArgs, _context: TContext, _info: GraphQLResolveInfo) {
      return {};
    };
  fc.resolve = async (source, args, context, info) => {
    const result = await oldResolve(source, args, context, info);
    result['query'] = {};
    if (!result['status']) result['status'] = 'Ok';
    return result;
  };
  (fc as ObjectTypeComposerFieldConfigAsObjectDefinition<any, TContext, TArgs>).type = type;
  return fc as ObjectTypeComposerFieldConfigAsObjectDefinition<any, TContext, TArgs>;
}
```

For today I need to go. It's midnight already. See you tomorrow.

**Comment by RobertLowe** [comment]
Thanks for the effort, sponsored the project, enjoy a few 🍻 or what you like!

**Comment by RobertLowe** [comment]
33f6659

- Ports changes from createOne to updateById & updateOne
- Use async `validate` over validateSync

In future we may want to allow for control over `validate` options. https://mongoosejs.com/docs/api/document.html#document_Document-validate ex: `validateModifiedOnly`

**Comment by nodkz** [comment]
> Thanks for the effort, sponsored the project, enjoy a few 🍻 or what you like!

Wow! Thanks a lot! 🙏
I'll take a look at your changes tomorrow... Nope, I'm not spending money on 🍻🍻🍻 😜. I had a quite terrible day by updating dependencies and resolving tons of conflicts and broken builds for our internal client package. For now, I exhausted and cannot concentrate on your PR.

**Comment by nodkz** [comment]
I changed the `payload.errors: [ErrorInterface]` to `payload.error: ErrorInterface` according to the following reasons:
- I need somehow to catch runtime errors inside the resolve method and return them to the user. And JS return just one error object. And wrap it in an array looks quite strange 😅
- Clients will get one error in most cases, so why they need Arrays?! And I'm sure, that just one error is more obvious and easy to use field. `errors` field on top-level in GraphQL response was created that exceptions may occur in different resolvers when graphql query is executed. BUT in our case, we have just one resolver. So no needs in an array 💃

So we according to current graphql schema design we return just one `error`. So what do you think about how to deal with many validation errors? Yep, just create `ValidationError` with some field inside for an array of sub-errors. And of course, return combined error msg in `message` field.

@RobertLowe what do you think?

**Comment by RobertLowe** [comment]
Thrown errors still happen at top level and are an array, ex:
```
{
  "errors": [
    {
      "message": "Authentication Error",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "getAuthToken"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "payload": [
            {
              "field": "password",
              "message": "Please enter a valid password."
            }
          ],
          "stacktrace": [
            "Error: Authentication Error",
            "    at GraphQLLocalStrategy.verify (../src/index.js:46:21)",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
          ]
        }
      }
    }
  ],
  "data": {
    "getAuthToken": null
  }
}
```

Where validation errors happen at the data level:

```
"data": {
  "usersCreateOne": {
    record: ..., recordId: ..., "errors": [{ "path": "email", "value": "There is already a user with this email." }],
    hasErrors: true
  }
}
```

Another idea would be to use `UserInputError`  https://www.apollographql.com/docs/apollo-server/data/errors/ However that feels like a lot for a frontend developer to dig through as well as it doesn't really work well for `...Many` operators.

My proposal is this:

```
"data": {
  "usersCreateMany": {
    items: [
    {record: ..., recordId: ..., "errors": [{ "path": "email", "value": "There is already a user with this email." }]},
    {record: ..., recordId: ..., "errors": [{ "path": "email", "value": "There is already a user with this email." }]}, 
   ],
   hasErrors: true
  }
}
```

Makes the most sense as it follows what the singular version would do:

```
"data": {
  "usersCreateOne": {
    record: ..., recordId: ..., "errors": [{ "path": "email", "value": "There is already a user with this email." }],
    hasErrors: true
  }
}
```

The benefit is your errors are related to their origin, it does create one more level, but I think that's just the cost of it.

Runtime, and MongoError's should be top-level. and not inside the `data` level.

This is the same as what `graphql-ruby` does: https://graphql-ruby.org/mutations/mutation_errors

Thanks again, and I'll defer to you as you know more than I.

**Comment by nodkz** [comment]
First of all, we should differentiate errors in `Queries` and `Mutations`:
- errors in `Query` are well described by Sasha Solomon in her [last talk about error handling](https://www.youtube.com/watch?v=RDNTP66oY2o). They are specific to Data Domains and it's quite hard to generate something reasonable according to just mongoose schema. So, for now, we do not consider such kinds of errors in graphql-compose-mongoose.
- errors in `Mutation`. The mutation we should consider as some **Operation on data changing**. You wrote about `validation errors happen at the data level` – but better to say `operation level`, `data level` its quite abstract thing.

So any operation on data changing can be finished with to statuses
- success with data, 
- or it may be failed by some exception. Programming languages allow us to throw just one error. And you may encapsulate as much additional information inside the error object as you need. 

Eg. mongoose's `validationError` is a good example of such cumulative error. You have `message` field with common error message – `User validation failed: n: Path n is required., valid: this is a validate message`:

Screen Shot 2020-08-26 at 12 32 06

and you may traverse `errors` field if you want to get specific parts of validation errors:

Screen Shot 2020-08-26 at 12 35 12

If we think about Mutations in terms of `operation` (in other words - `function call`, or `transaction execution`), so it has just two variants - `success` or `fail`. And according to graphql query language, we should provide the most convenient way for the consumption of these operation results eg. `{ record: Entity, error: ErrorInterface }`. Such payload structure is very simple (KISS). And allows to us return an error in the payload (if the user requested `error` field in graphql query) or otherwise throw it to top-level `errors` field. When we decided to provide the array of errors in payload, we didn't consider how to provide this array on top-level – we can throw just one error, but cannot throw an array of errors (javascript & graphql disallows such thing). So providing singular ErrorInterface in the payload is a good constraint – easy to implement in code for us, easy to read any kind of errors on client-side.

> Runtime, and MongoError's should be top-level. and not inside the data level.

As i wrote above I consider mutations from `operation level` not `data level`. Any errors inside operation execution belong to operation. Operations halted by some reason, so we should answer to the user why it happens in that way how it request. If it asks us to return `error` field in payload, then any error from operation should be returned in this field. And no matter what it was some validation error, or mongodb error, or some tricky business logic inside resolver. 

When we consider just `data level` so we restricted to throw just validation errors. So in such way we must rename our `errors` field to more expressive name - `validationErrors`. And think in what form we can throw them to top-level if user doesn't request this field in graphql query.

Moreover, if you watch Sasha's video they distinguish request parsing errors for top-level `errors` field (something like an incorrect request from the client) and operation errors for `data` field (something happens according to data domain and data itself). So `email already taken`, `password is too short`, `Mongo: E11000 duplicate id`, 'no db connection' I feel that they all are operational level errors. Because the client wants to execute some operation for data changing, server accepted the query, started execution, but something went wrong and operation was halted. What if the client sends several mutations inside one request and some of them were halted?!

PS. What to do with batch resolvers I try to think about this evening.

**Comment by RobertLowe** [comment]
Okay, right, this all makes sense. We can still dig into `error` for `error.errors`.

Thanks for these explanations, I know I must be absorbing your valuable time but I'm learning a great amount and the talk was fun to watch.

Yes, batch will be more tricky because they aren't done as a transaction but a `save` per entity meaning only some could complete. I'm not sure how things process/halt there of hand.

All said, we should end up with results like?:

```jsonc
"data": {
  "usersCreateOne": {
    record: ..., 
    recordId: ..., 
  "error": {
    __typename: "ValidationError", 
    message: "Validation failed, some longer message", 
    errors: [{ "path": "email", "value": "There is already a user with this email." }]}
  }
}
```

```jsonc
"data": {
  "usersCreateMany": {
    items: [
    {record: ..., recordId: ..., "error": { ... }},
    {record: ..., recordId: ..., "error": { ... }}, 
   ]
  }
}
```

**Comment by nodkz** [comment]
Yep, for singular resolvers we can use almost the same shape as mongoose returns for us (without transformation):
```ts
"data": {
  "usersCreateOne": {
    record: ..., 
    recordId: ..., 
    "error": {
      __typename: "ValidationError", 
      message: "Validation failed, some longer message", 
      errors: [{ "path": "email", "value": "There is already a user with this email." }]
    }
  }
}
```

For "batch" resolvers, I think, that we should keep the same shape for payload `{ recordS: ..., error: ...}` to know that some errors happen - eg. { message: 'Operation has 5 errors: Here go joined messages from 5 errors.' }. 

And also provide granularly error for every record in `records` field. How I wrote above `I suppose that records field which is an array of shape for singular response is quite a good and reusable solution (in the clients code developers can write helper functions which read singular mutations and reuse them in iterators for plural resolvers).`

So for "batch" resolvers the graphql query can be the following form:
```graphql
mutation {
  userCreateMany {
    error {
      message # String with a cumulative error message (which will be thrown to top-level if this field isn't requested)
    }
    records {
      record
      recordId
      error { # error object for specific record like in singular mutation resolvers
        message
        ... on ValidationError {
          path
          value
          message
        }
      }
    }
  }
}
```

**What we can do more for "cumulative error"?**
If we have only validation errors, we can combine all validation errors from different records with `path` modification and return regular `ValidationError` type. For example, if 3rd record has error then change `path: "n"` to `path: "3.n"` where 3 is an index of record from the input array. In such way we can throw on top-level correct validation error as we did for singular mutations.

**Comment by RobertLowe** [comment]
For the cumulative error message I think something like KISS like`"<number> of document(s) has issues."` is enough, but it's up to the developer to use the nested errors for more useful information, re: `MongoError` / `ValidationError`.

**Comment by RobertLowe** [comment]
Another thought, `projection` feels awkward no? I mean it's not a real mongo projection, is there some other way we can pass it in?

**Comment by nodkz** [comment]
> Another thought, projection feels awkward no? I mean it's not a real mongo projection, is there some other way we can pass it in?

Projection it's just parsed fields from graphql query (it's extracted from 4rd `info` param, from query AST. Supports regular queries, named fragments and inline fragments). This is quite a useful thing. How I remember, I decided how to name this param, and was choosing between `projection` & `select`. `projection` i liked more. If you have any suggestions on how it can b renamed or improved - let me know.

> Can you confirm if we should should always throw, that feels odd as well? Or only throw if that flag is set, elsewise just return the response with the error?

I don't understand the question. What exactly flag do you mean?

**Comment by RobertLowe** [comment]
> I don't understand the question. What exactly flag do you mean?

https://github.com/graphql-compose/graphql-compose-mongoose/pull/248/files#diff-dd2f0072f8e0f435a2b858dcba4c6aafR91-R106

Do we *need* to throw? That would go against Sasha Solomon's talks about hard and soft errors (errors and results)? Validation errors are soft in my opinion. So should we have a boolean to throw or not throw but return the response `{ record: null, recordId: null, error: ...}` successfully?

**Comment by nodkz** [comment]
@RobertLowe I've just implemented all I want with `payload.error` in https://github.com/graphql-compose/graphql-compose-mongoose/pull/248/commits/c2134a4411fc834b0c96423f7642dcca46a3cb6e

I managed to keep the resolvers as simple and clean as possible and put all logic in separate modules.

For understanding how works `payload.error` for the client – see carefully the following test suite https://github.com/graphql-compose/graphql-compose-mongoose/pull/248/files#diff-db6bb76152461b1e807ccac62fe81271

Ouch, i forgot, one small thing which didn't implemented – batch error for `createMany`. For now, it just returns the first caught error. For the implementation of `<number> of document(s) has issues` needs to completely rewrite `save` block. For now I'm exhausted, and frankly, I didn't know how to do it. However current implementation provides such error with `idx` in path:
```ts
    expect(res).toEqual({
      data: {
        createMany: {
          records: null,
          error: {
            __typename: 'ValidationError',
            message: 'User validation failed: someStrangeField: this is a validate message',
            errors: [
              {
                message: 'this is a validate message',
                path: '1.someStrangeField',
                //     ^^ - we add idx of broken record
                value: 'Test',
              },
            ],
          },
        },
      },
    });
```

**Comment by nodkz** [comment]
BTW I'm ready to merge it after your review ;)

**Comment by RobertLowe** [comment]
You're awesome, this is amazing work. I see what you mean re: https://github.com/graphql-compose/graphql-compose-mongoose/pull/248/files#diff-db6bb76152461b1e807ccac62fe81271 the throwing and catching makes sense now. I was overlooking the catch.

This all looks very good, but I do have some minor feedback:

Wouldn't it make more sense to include the index number?
```
    expect(res).toEqual({
      data: {
        createMany: {
          records: null,
          error: {
            __typename: 'ValidationError',
            message: 'User validation failed: someStrangeField: this is a validate message',
            errors: [
              {
                index: 1,
                message: 'this is a validate message',
                path: 'someStrangeField',
                //     ^^ - we add idx of broken record
                value: 'Test',
              },
            ],
          },
        },
      },
    });
```
alternatively, i think we should instead aim for:

```
    expect(res).toEqual({
      data: {
        createMany: {
          records: [{
            record: null,
            error: {
              __typename: 'ValidationError',
              message: 'User validation failed: someStrangeField: this is a validate message',
              errors: [
                {
                  message: 'this is a validate message',
                  path: 'someStrangeField',
                  value: 'Test',
              },
            ],
          }]
        },
      },
    });
```

And:

```
    expect(res).toEqual({
      data: {
        createMany: {
          records: null,
          error: {
            __typename: 'ValidationError',
            message: 'User validation failed: someStrangeField: this is a validate message',
            errors: [
              {
                index: 1,
                message: 'this is a validate message',
                path: 'someStrangeField',
                //     ^^ - we add idx of broken record
                value: 'Test',
              },
            ],
          },
        },
      },
    });
```

Elsewise do the rethrow approach.

I think the benefit of having the createMany just include many of createOne's structure makes a lot of sense. Frontend developers really shouldnt have an issue.

ex:

`RecordPayload` -> `record` -> `User` 
`RecordPayload` -> `error` -> `[ErrorInterface]` 

and for many:

'records` -> [RecordPayload]` -> `record` -> `User'
'records` -> `[RecordPayload]` -> `error` -> `[ErrorInterface]`

**Comment by nodkz** [comment]
@RobertLowe what do you think if we rewrite `createMany` resolver with https://mongoosejs.com/docs/api.html#model_Model.insertMany:
> Mongoose always validates each document before sending insertMany to MongoDB. So if one document has a validation error, no documents will be saved.

So we should choose one of the following strategies for `createMany`:
- **it should run only if all records are valid**. `createMany` helps us to implement this. And in such case, we just got one Error from mongoose.
- **it may save records partially**. In such case we should use `Payload` shape from your last comment (`records -> [RecordPayload] -> error -> [ErrorInterface]`). But it will require to write quite lot logic.

I like the first strategy. It will work like `updateMany` resolver which reuses `mongoose` logic without inventions from our side. Also, the first strategy helps to save similar `error` handling for all resolvers.

**Comment by RobertLowe** [comment]
@nodkz I looked into how `insertMany` throws it's error, given:

```
Test.insertMany([
  {valid: "foobar"},
  {invalid: "barfoo"},
  {invalid: "bazfoo"}
], function(a,b){ ... })
```

Mongoose will only throw a single error for the first document it has an issue with, it will not reference which document has an issue, just that one document did. This is bad because you're not able to match up errors to the document.

So, we should iterate documents, run `validate` on each, collect the errors, if one return  the payload shape like: `records -> [RecordPayload] -> error -> [ErrorInterface]` then if not, run `insertMany`, return the payload ``records -> [RecordPayload] -> record`

We can still use `projection.error` like before and either send the payload with errors or throw an error containing the all the errors. This gives use a singular place to manage MongoError/RunError/Validation**s**Error.

Regardless of the final structure we decide on, I think it's of value to run `validate` individually.

**Comment by nodkz** [comment]
Huh, quite complicated decision about what to do with `createMany` resolver. There are so many compromises.

For now, I think that the better solution will be the following payload:
```graphql
# We create records only all of them pass the validation step
type CreateManyPayload {
  # if any record has validation issue, then we return null here, no one record will be saved
  records: [Entity!]

  # without any interface you got [null, null, { ...validationErrorData }] if issue in the 3rd record
  # so you obtain index from array
  # There is no need to use ...on ValidationError fragment in query, because we can return here only validation error
  # Decision to provide `records -> [RecordPayload] -> error -> [ErrorInterface]` is quite overenginired
  validationErrors: [ValidationError]

  # cumulative error for providing the same behavior with other mutations
  # I'll keep the already implemented solution with idx injected in `path`
  # OR you may request `validationErrors` and obtain index from the array position
  # So the client may choose what solution better fits his needs – `error` or `validationErrors` or both of them.
  error: ErrorInterface

  # Client may request any data after mutation for obtaining a new server state.
  # I forgot about this feater it's described here https://graphql-rules.com/rules/mutation-payload-query
  query: Query 
}
```

As a conclusion: the most painful thing for me was `records -> [RecordPayload]`. We really can return just `records -> [{ record, validationError }]` here. BUT `RecordPayload` is more than just `record, validationError`. It may contain `query` field or any other fields related to operation - `duration`, `recievedArgs`, `tracingData`... Even more, it will be quite difficult to explain to clients how to properly use `records -> [RecordPayload]` and really just a few of them will use as we discussed it above. So we need to provide as simple Payload as we can.

@RobertLowe what you think? Can you simplify Payload more?

**Comment by RobertLowe** [comment]
If we must then I suggest:

```
type CreateManyPayload {
  # if any record has validation issue, then we return null here, no one record will be saved
  records: [Entity!]
  # can be a  `ManyValidationError`
  error: ErrorInterface
  query: Query 
}
```

Where `ErrorInterface` can be `ValidationsErrors` not to be confused with `ValidationError` we could even name it `ManyValidationError`, which would be:

```
type ManyValidationError extends Error {
  message: String,
  errors: [ValidationError]
}
```

Does that make sense? I don't really see the need for `validationsError` in that case.

Unless you want to avoid a hard error, in which case:
```
type CreateManyPayload {
  # if any record has validation issue, then we return null here, no one record will be saved
  records: [Entity!]
  validations: ManyValidationError # or `validationErrors` 
  # can be a  `ManyValidationError`
  error: ErrorInterface
  query: Query 
}
```

**Comment by nodkz** [comment]
@RobertLowe do you need precise validation for `createMany` in your app or you just want to provide the best experience to end-users?

I've just looked at mongoose's `insertMany` implementation and it has about [130 LoC of untrivial logic](https://github.com/Automattic/mongoose/blob/648e6e6d9f21eadd19ef7e2a600cc671ce39b032/lib/model.js#L3228-L3353) plus has 55 LoC for [`parallelLimit` method](https://github.com/Automattic/mongoose/blob/648e6e6d9f21eadd19ef7e2a600cc671ce39b032/lib/helpers/parallelLimit.js). All this logic should be copy-pasted to this library with support of the following mongoose internals: versionKey, initializeTimestamps, parallelLimit. And who knows what else will be added tomorrow. In the long term, it can be hard to maintain.

Frankly, I don't want to copy-paste mongoose internals here. So what I can do 
- if you really want to use `createMany` in your app with precise validation
  - I can implement simplified logic without `insertMany` method. All records will be saved via `Model.save()` method.
- if you just want to provide the best experience to end-users
  - we can leave the current implementation as is (just throw the first validation error). For most users will be enough the current implementation.
  - open feature/pull request for improving validation in mongoose library itself. And after implementation, use the improved `insertMany` mongoose method here.

**Comment by RobertLowe** [comment]
@nodkz if LoC is your business, this only cost another +28 lines and keeps it pretty simple

https://github.com/RobertLowe/graphql-compose-mongoose/blob/errors-payload-create-many/src/resolvers/createMany.ts

**Comment by RobertLowe** [comment]
Okay, did the refactor - https://github.com/RobertLowe/graphql-compose-mongoose/commit/0e91a47d480ef1e13326753d3d4953b291e6640e

We're only up +15

Payloads:

CreateOne:

```
error: {
  message: "User validation failed: valid: this is a validate message",
  errors: [
    { path, message, value }
  ],
}
```

CreateMany:

```
error: {
  message: "Cannot createMany some documents contain errors",
  errors: [
    null,
    {
      message: "User validation failed: valid: this is a validate message",
      errors: [{ path, message, value }],
    }
  ],
}
```

null's are used to keep order

**Comment by RobertLowe** [comment]
Also, what you think about changing the name of `errors` to `validations` to be more clear?

```
error: {
  message: "User validation failed: valid: this is a validate message",
  validations: [
    { path, message, value }
  ],
}
```

**Comment by nodkz** [comment]
I see that you choose the first scenario – and instead of using `insertMany` method you choose `model.create([ ... ])`. Good choice. It really helps to avoid copy-pasting mongoose internal logic (hooks, timestamps, versions, etc.) like it forced to do `insertMany` method. 

LoC is not my business. I'm trying to keep code as simple as possible. And avoid solutions that bring some code which should be implemented in another layer of abstraction (like precise validation for all records in `mongoose.insertMany` method).

Really `model.create([ ... ])` is a brilliant choice. I like it. @RobertLowe can you commit your changes to this PR? I'll polish code a little bit.

> Also, what you think about changing the name of `errors` to `validations` to be more clear?

Definitely, we should change `errors` for something another. `error.errors[x].errors.message` is really awkward. Possible solutions:
- `validation` – `error.validation[x].errors.message`
- `inputErrors` – `error.inputErrors[x].errors.message`
- `recordsErrors` – `error.recordsErrors[x].errors.message`
- `recordsValidations` – `error.recordsValidations[x].errors.message`
- `records` – `error.records[x].errors.message`

I like the `records` name, but `validation` looks good too.

PS. Thanks for sponsoring 🙏

**Comment by RobertLowe** [comment]
Phew, 3am here, I got done most of it.

https://github.com/graphql-compose/graphql-compose-mongoose/pull/248/commits/ec7b439ec961f5bdc021cb4eb6f46724df64df99

I didnt get a chance to rename `error.errors[x].errors.message` feel free to, I'm partial to `validation` over `record` as it doesn't contain any record information.

Messed up some minor typescript issues. Tests pass.

Otherwise I think this is a good pattern, we just need to apply it to `updateMany` as well.

Let me know your thoughts. 👍

**Comment by nodkz** [comment]
@RobertLowe please check `9.0.0-alpha.1`.

I refactored code, most things were simplified. And during the refactor, I found that your suggestion in https://github.com/graphql-compose/graphql-compose-mongoose/pull/248#issuecomment-682260789 (add `index` to `errors`) the most simple solution from all above that we discussed:
- less code in resolvers & helpers
- less types in graphql just one ErrorInterface (no need in ManyErrorInterface)
- less memory consumption (`errors: [ { idx: 3, message: '', path: ''} ]` better than `errors: [ null, null, null, { message: '', errors: [{ message: '', path: ''}] } ]`

If you want you may follow my last 8 commits for more information. As a summary, I can provide the following test case which demonstrates how validation errors result returned by `createMany` resolver:

```ts
 it('check validation for createMany', async () => {
    const res = await graphql.graphql({
      schema,
      source: `
        mutation { 
          createMany(records: [{ name: "Ok"}, { name: "John", someStrangeField: "Test" }]) { 
            records { 
              name
            }
            error {
              __typename
              message
              ... on ValidationError {
                errors {
                  message
                  path
                  value
                  idx
                }
              }
            }
          }
        }
      `,
    });

    expect(res).toEqual({
      data: {
        createMany: {
          records: null,
          error: {
            __typename: 'ValidationError',
            message: 'Nothing has been saved. Some documents contain validation errors',
            errors: [
              {
                message: 'this is a validate message',
                path: 'someStrangeField',
                value: 'Test',
                idx: 1, // <---------------------------- JUST ADDED `idx` field.
              },
            ],
          },
        },
      },
    });
  });
```

And such result when `error` field is not requested and resolver's error throws to top-level errors with extensions:

```ts
 it('check validation for createMany with root-level errors & extension', async () => {
    const res = await graphql.graphql({
      schema,
      source: `
        mutation { 
          createMany(records: [{ name: "Ok"}, { name: "John", someStrangeField: "Test" }]) { 
            records { 
              name
            }
          }
        }
      `,
    });

    expect(res).toEqual({
      data: { createMany: null },
      errors: [
        expect.objectContaining({
          message: 'Nothing has been saved. Some documents contain validation errors',
          extensions: {
            name: 'ValidationError',
            errors: [
              {
                idx: 1,
                message: 'this is a validate message',
                path: 'someStrangeField',
                value: 'Test',
              },
            ],
          },
          path: ['createMany'],
        }),
      ],
    });
  });
```

--

If you have any questions about current implementation – feel free to ask here.
If any additions (eg. what to do with `updateMany`) – please open a new one. 
This issue became too big.

**Thanks a lot for help with these amazing improvements** 🙏

**Pull request merged**
