### PR TITLE
Typeconverter options

### PR DESCRIPTION
**Pull request by mernxl**
While writing `mergeCustomizationOptions` function, i made the mistake of looking only at the `TypeConverterOptions` type Definition provided at `src/composeWithMongoose`.

You will find that `TypeConverterResolverOpts` type Definition, the Mutation resolvers have an `input` arg but implementation expects a `record` arg. 

I have done the necessary changes.

### CODE REVIEW

**Comment by nodkz** [comment]
Thanks!

**Comment by mernxl** [comment]
Ops, was still working on some more. lol. Next time i will put a `WIP`

**Comment by mernxl** [comment]
No Worries, Changes are abit different. Will do on new PR

**Pull request merged**
