### PR TITLE
Added regex operator support

### LINKED ISSUE #165: Support RegularExpression for filtering Operators
Hi,

I am just wondering if it's possible to support "like" for text fields in _operators when doing filtering?

that will be very useful for my use case.

thanks.

### PR DESCRIPTION
**Pull request by freitasmurillo**
Resolves #165

### CODE REVIEW

**Comment by nodkz** [comment]
Sorry I cannot accept this PR without tests.

I think it will not work because mongoose requires that value should be wrapped in `new RegExp(val)` class.

**Comment by freitasmurillo** [comment]
Agreed. I will make the tests.

About if it will work or not I can assure you that will because I am currently using my fork on my projects until it be available here.

**Comment by nodkz** [comment]
If you use your fork in the app and will switch back on the original package. In such case your feature definitely requires tests. It helps to avoid problems with somebody changes over the regexp filter.

**Comment by nodkz** [comment]
Close due test absence. Feel free to reopen the issue with tests ;)
Thanks.

**Comment by RobertLowe** [comment]
@nodkz I started on this and wrote tests, but after I wrote the simple implementation I started to think how to support `$options`. It's not as simple as `new RegExp(val)` as the signature is `new RegExp(pattern[, flags])`, we could hydrate `regex: "/thing/gi"` to `field: {$regex: "thing", $options: "gi"}` via [regex-parser](https://www.npmjs.com/package/regex-parser). But it feels awkward to do that handling inside of `processFilterOperators` and what would we do for invalid values like falsey, unparsable, etc.

So we need to type restrict `regex` to a String.

Could you give me some assistance to add this feature, I'm new to the internals. A few pointers would be great.

**Comment by nodkz** [comment]
@RobertLowe I think that we need to add some custom Scalar for regexp strings. For example this one https://github.com/Urigo/graphql-scalars/blob/master/src/RegularExpression.ts (I know Urigo and The Guild, they provide quite mature libraries).

Custom scalar takes care of value validation which supports graphql-js.

Please open the new Pull Request and let work there with this improvement. Try to somehow provide any working solution and then we polish it according to faced issues during your implementation.

Tnx!

**Pull request closed without merging**
