### PR TITLE
Make installable via git url

### PR DESCRIPTION
**Pull request by RobertLowe**
Straight forward, will let you install from a Git URL in your `package.json`

Cheers

PS: Dead code? : https://github.com/graphql-compose/graphql-compose-mongoose/blob/master/package.json#L10

### CODE REVIEW

**Comment by nodkz** [comment]
Wat?!... Amazing thing. I didn't know that such thing exists. Thanks!

**Comment by RobertLowe** [comment]
@nodkz Yeah, it's not documented on yarn! But they added support for it. I made a PR, they should mention it! https://github.com/yarnpkg/berry/pull/1770 most useful hook ever.

We should add it to all the repos?

Also, did you have a look at `"module": "mjs/index.mjs",` I don't think it's needed anymore?

**Comment by RobertLowe** [comment]
Hah, after more research this only works with yarn < 2.x and npm they dropped support for it which is foolish.

**Comment by arcanis** [comment]
> which is foolish

Always a pleasure.

Anyway, as I mentioned, the solution is to use `prepack`, which is portable.

**Comment by RobertLowe** [comment]
> Always a pleasure.

@arcanis gladly. In interesting of comparison I've tested a number of different configurations (no package.json using install/add, with package.json`, with `prepare` or `prepack` in each) on a clean directories for `npm`, `yarn`@1, `yarn`@2 and even `pnpm`.

All in all, `prepare` worked the most reliably here. I'm not sure what's up. It doesn't compile properly with `prepack`. The best portability was among `npm` & `yarn`@1, the worst `pnpm`.

**Pull request merged**
