### PR TITLE
Allow to opt-out of mutation payload.error

### LINKED ISSUE #286: Allow to opt-out of error schema generation for mutations
PR https://github.com/graphql-compose/graphql-compose-mongoose/pull/248 added an `error` field to mutations generated by graphql-compose-mongoose, including various types.

While I recognize this feature is cool, especially for fast prototyping, some of us may not need it.
In my case, I already have a complete error handling system for standard GraphQL errors (client & server side), and while I could just forget about that new way to collect errors (since the standard way to return the error is still used if `error` is not in the projection), I don't like having this totally unrelated way of handling errors in my API, this adds a layer of confusion and makes the schema slightly bigger.

It would be very nice to have a way to opt-out the schema generation of everything related to the `error` field, either via an option of `composeMongoose`, or via an option in the resolver factory function.

@nodkz PS: I've just upgraded to ^9.0.0 yesterday, it's a very good step forward! I was on a long vacation, so I'm sorry I didn't followed the discussions, but thanks a lot for the efforts you put in that new version. Also the migration was easy!

### PR DESCRIPTION
**Pull request by exneval**
Closes #286 

Need to complete before merge :
- [x] Add test case

Signed-off-by: Egi Ginting <exneval.rayz@gmail.com>

### CODE REVIEW

**Comment by nodkz** [comment]
Looks good! 👍
I'm ready to merge without tests but better to add them 😉
Tnx!

**Comment by exneval** [comment]
@nodkz thanks for reviewing

**Comment by nodkz** [comment]
Amazing! 👌
Thanks a lot

**Comment by toverux** [comment]
Thanks @exneval!

**Pull request merged**
