### PR TITLE
Nested projection

### PR DESCRIPTION
**Pull request by natac13**
Do not yet have a failing test. However, I have set mongoose debug to true which output the query being run for the `find` method.
This shows that the entire Author sub-document is being fetching and not just the requested `name` field.

I will keep working to get the testing to fail. Something with mocking the find I think... as it is not the return value from graphql that is wrong but from Mongodb itself.

Please run the 271-test.ts file to see what I mean.

**[UPDATE]**
I have got a Dotfiy function created. I current use this with my graphql server and mongoose (which I am trying switch to this library if I can cover my use cases). 
This function should get the nested structure of your incoming `projection` in `projectionHelper()`

There are some test failing now. Which I will look into resolving.

### CODE REVIEW

**Comment by natac13** [comment]
Just got one test failing now. 
It has to do with the virtual field override. 
```js
it('should make projection fields flat', () => {
      resolveParams.projection = { name: { first: 1, last: 1 } };
      projectionHelper(resolveParams, { name: 'n' });
      expect(spyFn).toBeCalledWith({ 'n.first': true, 'n.last': true });
 });
```

**Comment by natac13** [comment]
Closes #271

**Comment by natac13** [comment]
I am really unsure where you are first creating the `resolveParams.projection` when it is passed into the findMany resolve funciton.
Specifically I mean [here](https://github.com/graphql-compose/graphql-compose-mongoose/blob/4f08750a9ccc9b5836c050bc354e70537e10924e/src/resolvers/findMany.ts#L53). As I was trying to spyon the find method of BookModel but it is called without any args. I see how the projectionHelper function works but unsure where the original structure comes from.

**Comment by nodkz** [comment]
@natac13 it's creating in the core package when you try to get field config from resolver https://github.com/graphql-compose/graphql-compose/blob/3847bec760021be609a708e851a187edcbc09cfe/src/Resolver.js#L824-L833

I'm debugging all day aliases with discriminators. I found a [terrible bug](https://github.com/graphql-compose/graphql-compose-mongoose/pull/273/commits/d38e11716d48d1ae652a1dfe3fb7f14d655886c6) which blow my mind when I was trying to get an embedded model under an alias. And for now, I have a working solution. But need to write additional tests and clean up code. So stay tuned. I think in a couple of hours I'll publish a new package.

**Comment by natac13** [comment]
>@natac13 it's creating in the core package when you try to get field config from resolver https://github.com/graphql-compose/graphql-compose/blob/3847bec760021be609a708e851a187edcbc09cfe/src/Resolver.js#L824-L833

Thank you for showing me that. :+1: 

As for the terrible bug. Was this due to the changes I made?

>And for now, I have a working solution. But need to write additional tests and clean up code. So stay tuned. I think in a couple of hours I'll publish a new package.

Great news!! Thank you very much for this package!

**Comment by nodkz** [comment]
@natac13 can I ask you to review [release notes for v9.0.0](https://github.com/graphql-compose/graphql-compose-mongoose/blob/alpha/docs/releases/9.0.0.md)?

If you will have any questions, additions, or fixes – please write them here (or you may make fixes via PR for the `alpha` branch).
Thanks.

**Comment by natac13** [comment]
@nodkz no problem buddy. I'll read it over this weekend and get back to you by Monday.

**Pull request merged**
